### ISSUE TITLE
platform name error "xiaomi-purifier-3"

### ISSUE THREAD

**Issue by mitchoklemen** [github9984/homebridge-xiaomi-purifier-3#15]
Homebridge config request the PLATFORM name, without it I cant save config.
What are my options?

[9/25/2020, 6:17:11 PM] Error loading platform requested in your config.json at position 2
[9/25/2020, 6:17:11 PM] **Error: The requested platform 'xiaomi-purifier-3' was not registered by any plugin.**
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[9/25/2020, 6:17:11 PM] Got SIGTERM, shutting down Homebridge...

**Comment by mitchoklemen** [comment]
I tried also with platform 'homebridge-xiaomi-purifier-3' but it is the same!

**Comment by mitchoklemen** [comment]
Silly me! I've copied to 
Accessories: [
] 

Works!
Thank you, Mitcho
