### ISSUE TITLE
Hombridge fail: getBuzzer Failed: Error: This callback function has already been called by someone else

### ISSUE THREAD

**Issue by iShift** [github9984/homebridge-xiaomi-purifier-3#8]
```
Jun 14 15:24:10 raspberrypi homebridge[19877]: [6/14/2020, 3:24:10 PM] Got SIGTERM, shutting down Homebridge...
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at HAPServer.emit (events.js:315:20)
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:114
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at Array.forEach (<anonymous>)
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at On.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at On.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at On.emit (events.js:327:22)
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at AirPurifier.getBuzzer (/usr/local/lib/node_modules/homebridge-xiaomi-purifier-3/index.js:578:9)
Jun 14 15:24:10 raspberrypi homebridge[19877]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
Jun 14 15:24:10 raspberrypi homebridge[19877]: [6/14/2020, 3:24:10 PM] Error: This callback function has already been called by someone else; it can only be called one time.
Jun 14 15:24:09 raspberrypi homebridge[19877]: [6/14/2020, 3:24:09 PM] [Bed Room Air Purifier] getBuzzer Failed: Error: This callback function has already been called by someone else;
```

**Comment by iShift** [comment]
I solved my problem after remove:
```
            "enableLED": true,
            "enableBuzzer": true,
```

From config.

PS: @github9984 maybe we can have changelog, that shows in config-ui x plugin? because if we have any breaking changes, users can see it and adjust config.
